"""Deterministic trade/setup explanations (blueprint §62, §82).

Built entirely from the structured facts already computed by the SMC/ICT
and strategy engines — nothing here is generated by an LLM, so there is
nothing to hallucinate. An `AIClient` may be used *on top of* this to
rephrase it in natural language, but the facts themselves always come from
here.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.strategy.context import EvaluationContext
from app.strategy.engine import StrategyEvaluationResult


@dataclass(slots=True)
class TradeExplanation:
    market_context: str
    why_setup_exists: str
    conditions_satisfied: list[str]
    conditions_missing: list[str]
    risk: str
    invalidation: str
    potential_exit: str
    setup_score: float = field(default=0.0)


def build_trade_explanation(context: EvaluationContext, result: StrategyEvaluationResult) -> TradeExplanation:
    smc = context.smc

    market_context = (
        f"{context.symbol} on the {context.timeframe} timeframe is currently "
        f"{smc.bias or 'without a clear structural bias'}, trading at {context.current_price}."
    )

    if result.matched:
        why = (
            f"A {result.direction} setup formed: "
            + ", ".join(result.satisfied)
            + f". Entry {result.entry}, stop {result.stop}, target {result.target} "
            f"(risk/reward {result.risk_reward})."
        )
        risk = f"Risk is defined by the stop at {result.stop}; position size should reflect the account's configured risk-per-trade."
        invalidation = f"The setup is invalidated if price closes back through {result.stop} before reaching {result.target}."
        potential_exit = f"Primary exit at target {result.target}; consider trailing the stop once price moves favorably beyond 1R."
    else:
        why = "No setup currently satisfies all configured conditions."
        risk = "Not applicable — no trade is proposed."
        invalidation = "Not applicable."
        potential_exit = "Not applicable."

    return TradeExplanation(
        market_context=market_context,
        why_setup_exists=why,
        conditions_satisfied=result.satisfied,
        conditions_missing=result.missing,
        risk=risk,
        invalidation=invalidation,
        potential_exit=potential_exit,
        setup_score=result.score,
    )
