"""add strategy_version to orders and trades

Revision ID: 8f2667c1c07a
Revises: e5f2b195ea4e
Create Date: 2026-09-04 13:39:01.933547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f2667c1c07a'
down_revision: Union[str, None] = 'e5f2b195ea4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('strategy_version', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('strategy_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'strategy_version')
    op.drop_column('orders', 'strategy_version')
    # ### end Alembic commands ###
