"""add positions.protective_order_id

Revision ID: bae542907d14
Revises: c93a5f2e10b7
Create Date: 2026-09-12 03:43:22.761505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bae542907d14'
down_revision: Union[str, None] = 'c93a5f2e10b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('protective_order_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'protective_order_id')
    # ### end Alembic commands ###
