"""add user auto-trading settings

Revision ID: e5f2b195ea4e
Revises: fcb4617f63b9
Create Date: 2026-09-04 11:58:46.035945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5f2b195ea4e'
down_revision: Union[str, None] = 'fcb4617f63b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand so this doesn't fail against a users
    # table that already has rows (blueprint §102: existing users must
    # land with auto-trading OFF, never silently on).
    op.add_column('users', sa.Column('auto_trading_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('auto_trading_risk_per_trade_pct', sa.Numeric(precision=6, scale=3), nullable=False, server_default='0.5'))
    op.add_column('users', sa.Column('auto_trading_daily_loss_limit_pct', sa.Numeric(precision=6, scale=3), nullable=False, server_default='2.0'))
    op.add_column('users', sa.Column('auto_trading_max_trades_per_day', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('users', sa.Column('auto_trading_max_positions', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_trading_max_positions')
    op.drop_column('users', 'auto_trading_max_trades_per_day')
    op.drop_column('users', 'auto_trading_daily_loss_limit_pct')
    op.drop_column('users', 'auto_trading_risk_per_trade_pct')
    op.drop_column('users', 'auto_trading_enabled')
    # ### end Alembic commands ###
