"""initial schema

Revision ID: fcb4617f63b9
Revises: 
Create Date: 2026-09-04 11:32:51.939171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fcb4617f63b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('market', sa.Enum('EQUITY', 'FUTURES', 'OPTIONS', 'FOREX', 'CRYPTO', 'COMMODITY', name='market_type'), nullable=False),
    sa.Column('instrument_type', sa.String(length=32), nullable=False),
    sa.Column('underlying', sa.String(length=64), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('strike', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('option_type', sa.Enum('CALL', 'PUT', name='option_type'), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_table('option_chains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('underlying', sa.String(length=64), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('spot_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_chains_underlying'), 'option_chains', ['underlying'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'PENDING_VERIFICATION', name='user_status'), nullable=False),
    sa.Column('trading_permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.Enum('ANALYSIS', 'TRADE_PROPOSAL', 'STRATEGY_BUILD', 'EXPLANATION', name='ai_decision_type'), nullable=False),
    sa.Column('input_context', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decisions_user_id'), 'ai_decisions', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_user_id'), 'ai_messages', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.Enum('DHAN', 'UPSTOX', 'PAPER', name='broker_name'), nullable=False),
    sa.Column('encrypted_credentials', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCONNECTED', 'ERROR', name='broker_account_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'timestamp', name='uq_candle_key')
    )
    op.create_index(op.f('ix_candles_instrument_id'), 'candles', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SETUP_DETECTED', 'TRADE_EXECUTED', 'ORDER_REJECTED', 'POSITION_CLOSED', 'SL_HIT', 'TP_HIT', 'DAILY_LOSS_LIMIT', 'BROKER_DISCONNECTED', 'MARKET_DATA_STALE', 'AUTO_TRADING_DISABLED', 'RECONCILIATION_REQUIRED', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('option_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.UUID(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['option_chains.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_contracts_chain_id'), 'option_contracts', ['chain_id'], unique=False)
    op.create_index(op.f('ix_option_contracts_instrument_id'), 'option_contracts', ['instrument_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('execution_mode', sa.Enum('LIVE', 'PAPER', 'BACKTEST', 'REPLAY', name='portfolio_execution_mode'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_exposure', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_delta', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_gamma', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_theta', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_vega', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('execution_mode', sa.Enum('LIVE', 'PAPER', 'BACKTEST', 'REPLAY', name='position_execution_mode'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stop', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_instrument_id'), 'positions', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('replay_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('speed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PLAYING', 'PAUSED', 'FINISHED', name='replay_status'), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_sessions_user_id'), 'replay_sessions', ['user_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', name='risk_decision'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('related_order_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_user_id'), 'risk_events', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('setups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('setup_type', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setups_instrument_id'), 'setups', ['instrument_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('eligible_for_auto_trading', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('ticks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ltp', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('bid', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('open_interest', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticks_instrument_id'), 'ticks', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_ticks_timestamp'), 'ticks', ['timestamp'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_model', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='backtest_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_user_id'), 'backtests', ['user_id'], unique=False)
    op.create_table('option_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('option_contract_id', sa.UUID(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ltp', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('open_interest', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('iv', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('delta', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('theta', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_contract_id'], ['option_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_snapshots_option_contract_id'), 'option_snapshots', ['option_contract_id'], unique=False)
    op.create_table('replay_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('replay_session_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['replay_session_id'], ['replay_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_orders_replay_session_id'), 'replay_orders', ['replay_session_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='signal_direction'), nullable=False),
    sa.Column('bias', sa.String(length=16), nullable=True),
    sa.Column('entry', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stop', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('target', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('risk_reward', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_instrument_id'), 'signals', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_signals_strategy_id'), 'signals', ['strategy_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('execution_mode', sa.Enum('LIVE', 'PAPER', 'BACKTEST', 'REPLAY', name='trade_execution_mode'), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='trade_direction'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stop', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journal', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_instrument_id'), 'trades', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('backtest_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('sharpe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('average_win', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('average_loss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('average_r', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('long_trades', sa.Integer(), nullable=False),
    sa.Column('short_trades', sa.Integer(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('drawdown_curve', sa.JSON(), nullable=False),
    sa.Column('monthly_returns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('r_multiple', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_id'), 'backtest_trades', ['backtest_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=True),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('execution_mode', sa.Enum('LIVE', 'PAPER', 'BACKTEST', 'REPLAY', name='execution_mode'), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='order_direction'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'SL', 'SL_M', name='order_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'VALIDATING', 'RISK_APPROVED', 'SUBMITTED', 'ACKNOWLEDGED', 'PARTIALLY_FILLED', 'FILLED', 'MONITORING', 'CLOSED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'FAILED', name='order_status'), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_orders_instrument_id'), 'orders', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_instrument_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_backtest_trades_backtest_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_table('backtest_metrics')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_instrument_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_signals_strategy_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_instrument_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_replay_orders_replay_session_id'), table_name='replay_orders')
    op.drop_table('replay_orders')
    op.drop_index(op.f('ix_option_snapshots_option_contract_id'), table_name='option_snapshots')
    op.drop_table('option_snapshots')
    op.drop_index(op.f('ix_backtests_user_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_ticks_timestamp'), table_name='ticks')
    op.drop_index(op.f('ix_ticks_instrument_id'), table_name='ticks')
    op.drop_table('ticks')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_setups_instrument_id'), table_name='setups')
    op.drop_table('setups')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_risk_events_user_id'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_replay_sessions_user_id'), table_name='replay_sessions')
    op.drop_table('replay_sessions')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_instrument_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolio_snapshots_user_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_option_contracts_instrument_id'), table_name='option_contracts')
    op.drop_index(op.f('ix_option_contracts_chain_id'), table_name='option_contracts')
    op.drop_table('option_contracts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_instrument_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_messages_user_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_decisions_user_id'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_option_chains_underlying'), table_name='option_chains')
    op.drop_table('option_chains')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###

    # Alembic's autogenerate doesn't emit DROP TYPE for Postgres native
    # enums on downgrade (a known limitation) — without this, re-running
    # `upgrade` after a `downgrade` fails with "type already exists".
    for enum_name in (
        "market_type", "option_type", "user_role", "user_status", "ai_decision_type",
        "broker_name", "broker_account_status", "notification_type",
        "portfolio_execution_mode", "position_execution_mode", "replay_status",
        "risk_decision", "backtest_status", "signal_direction", "trade_execution_mode",
        "trade_direction", "execution_mode", "order_direction", "order_type", "order_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
